package com.example.shop.model.entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Base entity class that provides an id field.
 * This class is a mapped superclass, meaning that its fields will be mapped to the tables of its subclasses.
 */
@Data
@NoArgsConstructor
@MappedSuperclass
public abstract class BaseEntity {

    /**
     * The unique identifier for entities.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

}
